### ISSUE TITLE
Add a pgx driver

### ISSUE THREAD

**Issue by wokalski** [paurkedal/ocaml-caqti#38] opened 2020-05-09 12:41 UTC
The current postgres driver depends on `libpq` and `pg-config`. Statically linking `libpq` is very cumbersome. I believe that a pgx driver would be a minor but noticable quality of life improvement for many (including me).

**Comment by paurkedal** [comment] 2020-05-10 20:02
Yes, I have been planning on adding pgx support at some point.  My main motivation is to make it possible to run Caqti under MirageOS.  It will require some refactoring of how drivers are instantiated, but looking into this has become relevant now with the upcoming pgx release supporting it.

**Comment by yomimono** [comment] 2022-03-16 21:19
With `dream` wanting to target SQL databases via `caqti`, this has become even more relevant and desirable :)

**Comment by paurkedal** [comment] 2022-03-17 09:00
Yes, this will be high priority after the next minor release.  I have a sketch, but it needs more work, esp. on the driver API, which is currently C-binding centric.

**Comment by yomimono** [comment] 2022-03-17 17:32
That's great to hear! Please do let me know if there's any way I, as a PGX and MirageOS user who's also written against Caqti, can help. :)

**Comment by paurkedal** [comment] 2022-03-17 19:13
@yomimono Your help will be very welcome. I except to finish the upcoming release next week, and will post an update when I push my current work.

**Comment by paurkedal** [comment] 2022-04-19 17:50
There is now a [branch with the work-in-progress on the pgx driver](https://github.com/paurkedal/ocaml-caqti/tree/pgx).  Some of the remaining work I can think of at the top of my head:

  - Add TLS support. Pgx uses conduit for async, [but lacks TLS for lwt](https://github.com/arenadotio/pgx/issues/110) due to missing support for STARTTLS.
  - Preferably add support in pgx for reporting how many rows were affected by an update.
  - The code needs to be checked for uncaught exceptions caused by runtime issues.
  - The time zone should be set to UTC via the `setup` stub.
  - Check if there is something to implement for `reset`.

This branch breaks backwards compatibility, but I think only because an `` `Unsupported`` case was added to `Caqti_response_sig.S.affected_count` and `Caqti_connection_sig.Convenience.exec_with_affected_count`.

**Comment by paurkedal** [comment] 2022-06-08 14:23
The third item in the above list was resolved by delaying, in the PGX driver case, the request to the database from the start of the `call` invocation to the retrieval functions invoked by its callback.  This involves extending the range of errors allowed by retrieval functions to include request errors (non-backwards compatible), and documenting.

The `to_stream` function still needs to assemble the result into a list before returning, though.  This could be solved for lwt and async (or the upcoming multicore), but not for the current blocking.

**Comment by paurkedal** [comment] 2022-06-23 13:40
I created a branch [caqti2](https://github.com/paurkedal/ocaml-caqti/tree/caqti2) which will go into Caqti 2.0.0.  It includes pgx and mirage support.  For the latter I went for the "second approach" above.

**Closed** 2024-04-04 10:19 UTC
