### ISSUE TITLE
Caqti forcing the use of Format which is thread unsafe

### ISSUE THREAD

**Issue by craff** [paurkedal/ocaml-caqti#121] opened 2024-09-22 00:41 UTC
Caqti is forcing us to use Logs which in turn uses Format. But,
- Format is slower than printf (around 70% slower)
- More importantly, Format is thread unsafe and, for instance, may raise the exception Queue.Empty (I got that bug)
  I reported this problem, but I am not sure Logs is thread safe. 

Would be nice to be able to choose not to use Format.

**Comment by paurkedal** [comment] 2024-09-23 07:27
It can disable all logging by setting the level to `None` at startup.

As I understand it, the thread-safety of the logs library depends on the thread-safety of the registered reporter.  Still, if the reporter is not thread-safe, it looks like `Logs.set_reporter_mutex` can be used.

**Comment by paurkedal** [comment] 2024-10-25 07:02
I am closing this, assuming the issue was with the logs reporter.

By the way, logs was designed to only evaluate formatting for enabled messages.

**Closed by paurkedal** 2024-10-25 07:02 UTC
